version: '3'
services:
    mysql56:
        build:
            context: "./MySQL 5.6"
        environment:
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - db-data:/var/lib/mysql/data
        tty: true
    httpd-php:
        build:
            context: "./Apache24_PHP56_Redis"
        ports:
            - "80:80"
        tty: true
    tomcat:
        build:
            context: "./Tomcat 8"
        ports:
            - "8080:8080"
        tty: true
volumes: 
    db-data: