version: '3'
services:
    mysql56:
        build:
            context: "./MySQL 5.6"
        environment:
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - db-data:/var/lib/mysql/data
        networks:
            app_net:
                ipv4_address: 172.18.0.2
        tty: 'true'
    httpd-php:
        build:
            context: "./Apache 2.4 PHP 5.6"
        links:
            - mysql56:mysql
        ports:
            - "80:80"
        tty: 'true'
volumes: 
    db-data: